<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Most</strong> active people' => '<strong>Usuarios</strong> más activos',
    'Back to modules' => 'Volver a módulos',
    'Get a list' => 'Abrir lista',
    'Most Active Users Module Configuration' => 'Configuración del módulo Usuarios más activos',
    'Save' => 'Guardar',
    'The number of most active users that will be shown.' => 'El número de los usuarios más activos que se mostrará.',
    'You may configure the number users to be shown.' => 'Puedes configurar el número de usuarios para mostrar.',
];
