<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Most</strong> active people' => 'Pessoa <strong>mais<strong> ativa',
    'Back to modules' => 'Voltar aos módulos',
    'Get a list' => 'Listar',
    'Most Active Users Module Configuration' => 'Modulo de configuração de usuários mais ativos',
    'Save' => 'Gravar.',
    'The number of most active users that will be shown.' => 'Número máximo de usuários mais ativos que será apresentado.',
    'You may configure the number users to be shown.' => 'Você pode configurar o número de usuários para ser apresentado.',
];
