<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Most</strong> active people' => '<strong>Meest</strong> actieve personen',
    'Back to modules' => 'Terug naar modules',
    'Get a list' => 'Lijst',
    'Most Active Users Module Configuration' => 'Meest Actieve Gebruikers Module Configuratie',
    'Save' => 'Bewaar',
    'The number of most active users that will be shown.' => 'Het aantal van de meest actieve gebruikers die getoond zullen worden.',
    'You may configure the number users to be shown.' => 'Je kan het aantal gebruikers dat getoond zal worden configureren.',
];
