<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Most</strong> active people' => 'فعال‌ترین کاربرها',
    'Back to modules' => 'بازگشت‌ به ماژول‌‌ها',
    'Get a list' => 'یک لیست تهیه کنید',
    'Most Active Users Module Configuration' => 'تنظیمات ماژول فعال‌ترین کاربرها',
    'Save' => 'ذخیره',
    'The number of most active users that will be shown.' => 'تعداد فعال‌ترین کاربرانی که نمایش داده‌می‌شود.',
    'You may configure the number users to be shown.' => 'شما می‌توانید تعداد کاربران نمایش‌داده‌شده را تنظیم کنید.',
];
