<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '<strong>Most</strong> active people' => '',
  'Get a list' => '',
  'Most Active Users Module Configuration' => '',
  'No users.' => '',
  'Save' => '',
  'The number of most actice users that will be shown.' => '',
  'The number of users must not be greater than a 7.' => '',
  'The number of users must not be negative.' => '',
  'You may configure the number users to be shown.' => '',
);
